config/routes.rb
Rails.application.routes.draw do
  root to: 'home#home', as: 'home'
  get 'welcome/:name', to: 'home#welcome'
  get 'potin/:index', to: 'home#potin'
  get 'user/:index', to: 'home#user'


  get '/team', to: 'trivials#team', as: 'team'
  get '/contact', to: 'trivials#contact', as: 'contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
    belongs_to :tag
    belongs_to :potin
end

app/models/potin.rb
class Potin < ApplicationRecord
    belongs_to :user
    has_many :tags, through: :gossip_tag
end

app/models/relation.rb
class Relation < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :potins, through: :gossip_tag
end

app/models/user.rb
class User < ApplicationRecord
    has_many :potins
end

app/controllers/home_controller.rb
class HomeController < ActionController::Base
    def home
        @gossips = Potin.all
        @users = User.all
    end
    def welcome
        @name = params[:name]
    end
    def potin
        @potin = Potin.where(id: params[:index])[0]
        @user = User.where(id: @potin.user_id)[0]
    end
    def user  
        @user = User.where(id: params[:index])[0]
    end
end

app/controllers/trivials_controller.rb
class TrivialsController < ActionController::Base
    def team
        #static, you mf :slight_smile:
    end
    def contact
        #it's trivial omg, static lmao
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/home.html.erb
<h1> the gossip project</h1>

liste des gossips:
<% @gossips.each do |t| %>

<div class="gossip">
 <div class="title">
    <%= t.title %>
 </div>
 par : <%=@users.select { |u| u.id == t.user_id }[0].first_name%>
 <div class="prompt">
    <a href="/potin/<%= t.id%>"> lire le potin </a>
 </div>
</div>
<% end %>

app/views/home/potin.html.erb
<h2>
    potin par : <%=@user.first_name%> <%=@user.last_name%>
</h2>

<h1>
    <%=@potin.title%>
</h1>

<p>
    <%=@potin.content%>
</p>

created at : <%=@potin.created_at%>

app/views/home/user.html.erb
<h1> <%=@user.first_name%> <%=@user.last_name%> </h1>
<h3> <%=@user.age%> </h3>
<p> <%=@user.description%> </p>

app/views/home/welcome.html.erb
<h2> Bienvenue, <%=@name%>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gossip</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="header">
    <span class="brand">
      The Gossip Project
    </span>
  </div>
  <div class="nav">
    <div class="content">
    <a href="<%= home_path %>">
      <div class="item">
        Accueil
      </div>
    </a>
    <a href="<%= contact_path %>">
      <div class="item">
        contact
      </div>
    </a>
    <a href="<%= team_path %>">
      <div class="item">
        Notre equipe
      </div>
    </a>
    </div>
  </div>
  <div class="content">
    <%= yield %>
  </div>
  </body>
</html>

app/views/layouts/trivials.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gossip</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="header">
    <span class="brand">
      The Gossip Project
    </span>
  </div>
  <div class="nav">
    <div class="content">
    <a href="<%= home_path %>">
      <div class="item">
        Accueil
      </div>
    </a>
    <a href="<%= contact_path %>">
      <div class="item">
        contact
      </div>
    </a>
    <a href="<%= team_path %>">
      <div class="item">
        Notre equipe
      </div>
    </a>
    </div>
  </div>
  <div class="content">
    <%= yield %>
  </div>
  </body>
</html>

app/views/trivials/contact.html.erb
borismariondorier@gmail.com demerdez vous

app/views/trivials/team.html.erb
alors, il y a Paul Koo, AKA le sensei des DB <br> <br>

il y a aussi Benedicte, AKA le C c mieux (qui a raison) <br> <br>

et il y a Boris, AKA je pige rien aux DB